name: "Docs build job"
description: "Build the documentation."
runs:
  using: "composite"
  steps:
    - run: sphinx-apidoc -o docs/source src/tomato -T -M
      shell: bash
    - run: sphinx-build -b html docs/source public/master
      shell: bash
